"""add staff cpf

Revision ID: 286c66836d0b
Revises: 75b14aef61a9
Create Date: 2026-07-24 02:10:16.042272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286c66836d0b'
down_revision: Union[str, None] = '75b14aef61a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_members', sa.Column('cpf', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'staff_members', ['cpf'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff_members', type_='unique')
    op.drop_column('staff_members', 'cpf')
    # ### end Alembic commands ###
